### ISSUE TITLE
Compress

### ISSUE THREAD

**Issue by stephensaid** [niro1987/VirtualBox-Backup#6]
Hi, 

I was looking for a VM backup solution and stumbled upon your solution.
I love how it works and would like to use it but cannot compress the files.

I've got this command line in:
"%_VBBACKUP%" --backupdir "D:\VM-Backups" --backupmode acpipowerbutton --prefix "Manual Backup" --keep=6 --compress=7 --include "Name_of_VM"

I have 7z installed. I also downloaded '7z1900-extra' and placed it in a subfolder next to the batch files.
I also tried to place the files in the same folder of the batch files.
Not sure what to do to make compression work.

Any help would be greatly appreciated.

Thanks
Stephen

**Comment by niro1987** [comment]
Hi, sorry to reply so late. The 7-Zip Extra file `7z1900-extra.7z` should be extracted to `C:\Program Files\7-Zip\` as this is the default installation folder for 7-Zip. As per line 7 of the code `SET "_7za=C:\Program Files\7-Zip\7za.exe"` it is expecting the `7za.exe` file to be in this location.

**Comment by niro1987** [comment]
Looking at the docs, 7-Zip Extra should no longer be required. I'll change the code.

**Comment by niro1987** [comment]
Fixed in #8

**Comment by stephensaid** [comment]
Thanks, Niro

I have 7z.exe at the location you mentioned. 
I now downloaded the new version #8 you updated.
When I run the script I get a quick glimpse of the terminal window and then it closes and nothing happens.

Thanks for looking into this.
